spring.application.name=cab-service
# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${CAB_DB:cab_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8089

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
logging.level.org.springframework.boot.autoconfigure.kafka=DEBUG
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer