# Server
server.port=8080
spring.main.web-application-type=reactive
# App name
spring.application.name=gateway-service

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[2].id=cab-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/cab/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
jwt.secret=${JWT_SECRET}

spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=20

spring.cloud.gateway.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=10

spring.cloud.gateway.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.replenishRate=3
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=5


# Circuit breaker filter on cab-service (routes[2])
spring.cloud.gateway.routes[2].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[1].args.name=cabServiceCB
spring.cloud.gateway.routes[2].filters[1].args.fallbackUri=forward:/fallback/cab


# Register circuit breaker instance
resilience4j.circuitbreaker.instances.cabServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.cabServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cabServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.cabServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cabServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cabServiceCB.permittedNumberOfCallsInHalfOpenState=3


spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=authServiceCB
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/auth

resilience4j.circuitbreaker.instances.authServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.authServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.authServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authServiceCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.authServiceCB.permittedNumberOfCallsInHalfOpenState=2
